# Generated by Django 2.1.4 on 2018-12-23 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='id',
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Endereco'),
        ),
    ]
