# Generated by Django 2.1.4 on 2019-01-08 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181223_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
